services:

  jupyter:
    build:
      context: ./jupyter
      dockerfile: Dockerfile
    image: ${IMAGE_NAME}:latest
    ports:
      - "8889:8888"
    working_dir: /home/jovyan/${IMAGE_NAME}
    volumes:
      - ".:/home/jovyan/${IMAGE_NAME}"
    environment:
      - JUPYTER_ENABLE_LAB=yes
